# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(655, 395)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_Start = QtWidgets.QPushButton(self.tab)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.gridLayout_2.addWidget(self.pushButton_Start, 1, 0, 1, 1)
        self.pushButton_TEST = QtWidgets.QPushButton(self.tab)
        self.pushButton_TEST.setToolTip("")
        self.pushButton_TEST.setToolTipDuration(5)
        self.pushButton_TEST.setStatusTip("Tests wether everything is working as expected, if Test fails or App crashes please recheck settings ")
        self.pushButton_TEST.setObjectName("pushButton_TEST")
        self.gridLayout_2.addWidget(self.pushButton_TEST, 2, 1, 1, 1)
        self.pushButton_Stop = QtWidgets.QPushButton(self.tab)
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.gridLayout_2.addWidget(self.pushButton_Stop, 1, 1, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_2.addWidget(self.lcdNumber, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.timeEdit_Start = QtWidgets.QTimeEdit(self.tab_2)
        self.timeEdit_Start.setObjectName("timeEdit_Start")
        self.gridLayout.addWidget(self.timeEdit_Start, 7, 0, 1, 1)
        self.pushButton_Apply = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Apply.setObjectName("pushButton_Apply")
        self.gridLayout.addWidget(self.pushButton_Apply, 8, 1, 1, 1)
        self.lineEdit_cookieDirectory = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_cookieDirectory.setAutoFillBackground(False)
        self.lineEdit_cookieDirectory.setObjectName("lineEdit_cookieDirectory")
        self.gridLayout.addWidget(self.lineEdit_cookieDirectory, 0, 0, 1, 2)
        self.lineEdit_meetingLink = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_meetingLink.setObjectName("lineEdit_meetingLink")
        self.gridLayout.addWidget(self.lineEdit_meetingLink, 2, 0, 1, 3)
        self.dateEdit = QtWidgets.QDateEdit(self.tab_2)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 5, 0, 1, 1)
        self.pushButton_Reset = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        self.gridLayout.addWidget(self.pushButton_Reset, 8, 2, 1, 1)
        self.pushButton_Browse = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Browse.setObjectName("pushButton_Browse")
        self.gridLayout.addWidget(self.pushButton_Browse, 0, 2, 1, 1)
        self.timeEdit_End = QtWidgets.QTimeEdit(self.tab_2)
        self.timeEdit_End.setObjectName("timeEdit_End")
        self.gridLayout.addWidget(self.timeEdit_End, 7, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LazyMeet"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start"))
        self.pushButton_TEST.setText(_translate("MainWindow", "TEST"))
        self.pushButton_Stop.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Home"))
        self.pushButton_Apply.setText(_translate("MainWindow", "Apply"))
        self.lineEdit_cookieDirectory.setText(_translate("MainWindow", "Enter Chrome Cookie directory.."))
        self.lineEdit_meetingLink.setText(_translate("MainWindow", "Enter Google Meet , Meeting link here"))
        self.pushButton_Reset.setText(_translate("MainWindow", "Reset to Defaults"))
        self.pushButton_Browse.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "Select Date"))
        self.label_2.setText(_translate("MainWindow", "Select Start Time"))
        self.label_3.setText(_translate("MainWindow", "Select End Time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

